In [1]:
 import numpy as np

In [8]:
n = 10
a = np.random.normal(0, 1, (n, n))
A = a @ a.T
np.set_printoptions(suppress=True, linewidth = 185)
print(A)

[[ 3.6112473  -0.75381963  1.91962459 -4.19197611  0.96708965 -1.99804933 -0.07134246  1.00877051  2.11546816 -2.30094943]
 [-0.75381963 10.61441389  0.99654251 -2.07428773  0.67768027 -0.71661772  1.87968193  0.21616627  1.31935768  3.22823203]
 [ 1.91962459  0.99654251 11.53543608 -4.18540005 -0.85256095 -1.28857009  3.10940103  0.12783346  0.96348887 -2.86037981]
 [-4.19197611 -2.07428773 -4.18540005  8.58208663  2.68266848  1.24781462 -0.56686488 -0.55777938 -3.52729523  2.12997474]
 [ 0.96708965  0.67768027 -0.85256095  2.68266848 13.19996769 -5.4994902   1.32534996  1.36761787 -4.05852308 -4.95976363]
 [-1.99804933 -0.71661772 -1.28857009  1.24781462 -5.4994902  12.78101908 -2.32437806 -0.81061802 -1.66460925  4.1020766 ]
 [-0.07134246  1.87968193  3.10940103 -0.56686488  1.32534996 -2.32437806  2.30095434  0.9665642  -0.34536565 -0.84483397]
 [ 1.00877051  0.21616627  0.12783346 -0.55777938  1.36761787 -0.81061802  0.9665642   2.28484719  0.21851739  0.0817203 ]
 [ 2.11546816  1

In [9]:
s1 = np.linalg.eigvalsh(A)
print(s1)

[ 0.03315321  0.14107292  0.26388269  2.00659913  3.1164641   6.46589638  9.70667695 12.50863557 19.40167619 22.99597647]


In [22]:
from scipy.linalg import hessenberg
H, Q1 = hessenberg(A, calc_q=True)
for j in range(1000):
  (Q, R) = np.linalg.qr(H)
  H = R @ Q
  sum = 0
 #for i in range(n-1):
    #sum += H[i+1, i]
    #If abs(sum) < 1e-3:
     # break
print(H)
s2 = np.linalg.eigvalsh(H)
print(s2)

[[22.99597647 -0.          0.         -0.         -0.         -0.         -0.          0.         -0.         -0.        ]
 [ 0.         19.40167619  0.         -0.         -0.          0.          0.         -0.         -0.          0.        ]
 [ 0.         -0.         12.50863557  0.          0.          0.          0.         -0.          0.          0.        ]
 [ 0.          0.          0.          9.70667695  0.         -0.         -0.         -0.         -0.          0.        ]
 [ 0.          0.          0.         -0.          6.46589638  0.          0.          0.         -0.         -0.        ]
 [ 0.          0.          0.          0.         -0.          3.1164641   0.         -0.         -0.          0.        ]
 [ 0.          0.          0.          0.          0.         -0.          2.00659913 -0.         -0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.          0.          0.26388269 -0.         -0.        ]
 [ 0.          0