In [1]:
import numpy as np
import random

In [2]:
n = 100
D = np.identity(n)
for i in range(n):
  D[i, i] = random.random()
print(D)
u = np.random.rand(n)
print(u)

[[0.7728712  0.         0.         ... 0.         0.         0.        ]
 [0.         0.15484164 0.         ... 0.         0.         0.        ]
 [0.         0.         0.1818467  ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.82926862 0.         0.        ]
 [0.         0.         0.         ... 0.         0.24670359 0.        ]
 [0.         0.         0.         ... 0.         0.         0.31436429]]
[0.50182503 0.43716267 0.48405955 0.05885692 0.87436384 0.41813911
 0.39675969 0.4407038  0.57054638 0.07341563 0.36747134 0.27590822
 0.49797869 0.33427699 0.19480525 0.89444318 0.31826228 0.06853825
 0.78751956 0.41142427 0.94338245 0.94529419 0.70188008 0.81594444
 0.79353063 0.46976168 0.87517563 0.14824499 0.76923495 0.11308288
 0.21118993 0.94299429 0.83074373 0.60072077 0.81852922 0.88602465
 0.60953076 0.33686968 0.21449653 0.17183747 0.84069476 0.06035627
 0.50341923 0.05065981 0.34735467 0.46283172 0.82561851 0.08246383
 0.79188267 0.941505

In [3]:
u_t = u.reshape(n, 1)
print(u_t.shape)
u_ = u.reshape(1, n)
print(u_.shape)

(100, 1)
(1, 100)


In [4]:
A = D + (u_t @ u_)/(u_ @ u_t)
s = np.sort(np.diag(D))
print(s)

[0.00810533 0.01213309 0.016486   0.02197672 0.02340981 0.06984899
 0.07024564 0.07585204 0.07837962 0.09531912 0.09632132 0.10009039
 0.10929001 0.13399823 0.1453739  0.15484164 0.1565251  0.15849085
 0.1702049  0.18041443 0.1818467  0.18533692 0.19492484 0.20156927
 0.21114627 0.23235368 0.24670359 0.26293303 0.26870006 0.27912912
 0.2847465  0.30000428 0.31436429 0.31781573 0.33679207 0.3420987
 0.35985371 0.37483054 0.38505861 0.41605667 0.42516626 0.43817866
 0.44054366 0.44511018 0.44717888 0.4599186  0.48417353 0.48443528
 0.50284329 0.50309739 0.52498924 0.52667943 0.52727241 0.53998619
 0.54181778 0.54234089 0.55890789 0.55943368 0.579142   0.58174306
 0.58240093 0.58243288 0.59645342 0.60824488 0.63924005 0.64146824
 0.64277041 0.64380277 0.66627039 0.69070907 0.69595822 0.70565541
 0.7089952  0.73172869 0.74242387 0.74772488 0.75375437 0.76759755
 0.76787124 0.7728712  0.78961907 0.80563223 0.8072398  0.81546859
 0.82408097 0.82926862 0.84223388 0.84895854 0.85239954 0.87217

In [5]:
def norm(v):
 return np.sqrt(np.sum(v**2))
def inverse_iter(a, vec, mu, eps=1e-3, maxiter=1000):
 a = np.asarray(a, dtype=float)
 if a.ndim != 2:
  raise ValueError("a.ndim = %s, expected 2" % a.ndim)

 vec = np.asarray(vec, dtype=float)
 if vec.ndim != 1:
  raise ValueError("vec.ndim = %s, expected 1" % vec.ndim)

 if (a.shape[0] != a.shape[1]):
  raise ValueError("a is not square")

 if (a.shape[0] != vec.shape[0]):
  raise ValueError("vec should be of length %s" % a.shape[0])


 x = np.array(vec, dtype=float, copy = True)
 lam = mu
 iters = 0

 for i in range(maxiter):
  y = np.linalg.solve(a - lam * np.identity(a.shape[0]), x)
  lam_pr = lam
  lam = x @ (a @ x)
  x = y / norm(y)
  iters = i
  if(abs(lam - lam_pr) < eps):
    break;
 
 return(lam, x, iters)

In [6]:
vec = np.random.rand(n)
lam, x, _ = inverse_iter(A, vec, 0.0089)
print(lam)

0.012749995229181141


In [7]:
n = 10000 #для 100000 у меня не выдерживает ноутбук
D = np.identity(n)
for i in range(n):
  D[i, i] = random.random()
print(D)
u = np.random.rand(n)
print(u)

[[0.91932066 0.         0.         ... 0.         0.         0.        ]
 [0.         0.16940598 0.         ... 0.         0.         0.        ]
 [0.         0.         0.44888464 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.68355254 0.         0.        ]
 [0.         0.         0.         ... 0.         0.67005402 0.        ]
 [0.         0.         0.         ... 0.         0.         0.41246668]]
[0.89020632 0.14236112 0.10547346 ... 0.20802988 0.05014866 0.45094919]


In [8]:
u_t = u.reshape(n, 1)
u_ = u.reshape(1, n)
A = D + (u_t @ u_)/(u_ @ u_t)

s = np.sort(np.diag(D))
print(s)
print(s[-1])


[4.84345590e-05 7.36684056e-05 9.25354858e-05 ... 9.99908868e-01
 9.99929429e-01 9.99994996e-01]
0.9999949955709302


In [9]:
A_ = A - np.identity(n)
print(np.diag(A_))

[-0.08043913 -0.83058788 -0.55111199 ... -0.31643434 -0.32994522
 -0.58747168]


In [10]:
x = np.array([1] * n)
mod = norm(u)
lam = 10000000
for i in range(1000):
  k = np.zeros(n)
  for j in range(n):
    k[j] = x[j] * (D[j, j] - 1)
  y = k + (u_t @ u_)/(u_ @ u_t) @ x
  lam_pr = lam
  lam = x @ y
  x = y / norm(y)
  if(abs(lam - lam_pr) < 1e-4):
    break

print(lam)
print(lam + 1)

-0.9938137940362666
0.006186205963733427
