In [6]:
import numpy as np
import math

In [8]:
c = np.array([[1, 0.9, 0.7],[0.9, 1, 0.4],[0.7, 0.4, 1]])
c_ = c.copy()
c_[1][2] = 0.3
c_[2][1] = 0.3
lam = np.linalg.eig(c_)[0]
S = np.linalg.eig(c_)[1]
print(lam)
print(S)

[ 2.29672779 -0.00735244  0.71062465]
[[ 0.65991684  0.74767038 -0.0741536 ]
 [ 0.57099598 -0.5632171  -0.5972856 ]
 [ 0.48833733 -0.35181742  0.79859323]]


In [10]:
lam[1] = 0
s = S.T
for j in range(3):
  s[j] = s[j] * math.sqrt(lam[j])
print(s)

[[ 1.51564936  1.31142234  1.12157791]
 [ 0.         -0.         -0.        ]
 [-0.05269537 -0.42444587  0.56750004]]


In [11]:
s = s.T
for i in range(3):
  n = s[i, 0] ** 2 + s[i, 1] ** 2 + s[i, 2] ** 2
  if n != 0:
    s[i] = s[i] * (1/math.sqrt(n))
    
c_1 = s.dot(s.T)
print(c_1)

[[1.         0.96153494 0.87605522]
 [0.96153494 1.         0.70990276]
 [0.87605522 0.70990276 1.        ]]


При замене отрицательных собственных значений на нули и смене базиса обратно на i, j, k, мы можем вынести из диагональной матрицы с собственными значениями на диагонали эти собсвтенные значения и в итоге получить единичную матрицу.